Repository ASCENDynamics-NFP/AscendCoopPlatform, pull requests merged in 2024-02, with the labels that each got.

#214 updated navigation to registration page from login/signup
  .firebase/hosting.d3d3.cache
  functions/src/auth/user/triggers/onCreate/index.ts
  src/app/models/account.model.ts
  src/app/modules/account/pages/registration/registration.page.ts
  src/app/modules/group/pages/group/group.page.spec.ts
  src/app/modules/user/pages/user-login/user-login.page.ts
  src/app/modules/user/pages/user-profile/user-profile.page.ts
Labels: Priority: High, Refactor, Status: Code Review, Effort: Easy, Role: Developer

#217 updated account model and user edit page
  firestore.rules
  functions/src/auth/user/triggers/onCreate/index.ts
  src/app/core/services/firestore.service.ts
  src/app/models/account.model.ts
  src/app/models/base-document.ts
  src/app/models/feedback.model.ts
  src/app/modules/account/pages/registration/registration.page.html
  src/app/modules/account/pages/registration/registration.page.scss
  src/app/modules/account/pages/registration/registration.page.ts
  src/app/modules/group/components/create-group-modal/create-group-modal.component.ts
  src/app/modules/group/pages/group-edit/group-edit.page.html
  src/app/modules/group/pages/group-edit/group-edit.page.ts
  src/app/modules/group/pages/group-profile/components/details/details.component.html
  src/app/modules/group/pages/group-profile/components/details/details.component.ts
  src/app/modules/group/pages/group-profile/components/hero/hero.component.html
  src/app/modules/user/pages/edit-user-profile/edit-user-profile.page.html
  src/app/modules/user/pages/edit-user-profile/edit-user-profile.page.ts
  src/app/modules/user/pages/user-login/user-login.page.html
  src/app/modules/user/pages/user-profile/components/details/details.component.html
  src/app/modules/user/pages/user-profile/components/details/details.component.ts
  src/app/modules/user/pages/user-profile/components/hero/hero.component.html
  src/app/modules/user/pages/user-settings/components/settings/settings.component.html
  src/app/modules/user/pages/user-settings/components/settings/settings.component.ts
  src/app/shared/components/app-header/app-header.component.scss
  src/global.scss
  src/theme/variables.scss
Labels: Documentation, Enhancement, Priority: High, Status: In Progress, Effort: Medium, Role: Developer

#219 206 create register group component
  src/app/core/services/auth-store.service.ts
  src/app/core/utils/firebase.util.ts
  src/app/models/account.model.ts
  src/app/modules/account/pages/registration/components/group-registration/group-registration.component.html
  src/app/modules/account/pages/registration/components/group-registration/group-registration.component.scss
  src/app/modules/account/pages/registration/components/group-registration/group-registration.component.ts
  src/app/modules/account/pages/registration/registration.page.spec.ts
  src/app/modules/account/pages/registration/registration.page.ts
  src/app/modules/group/pages/group-edit/group-edit.page.html
  src/app/modules/group/pages/group-edit/group-edit.page.ts
  src/app/modules/user/pages/edit-user-profile/edit-user-profile.page.html
  src/app/modules/user/pages/user-login/user-login.page.html
  src/app/modules/user/pages/user-login/user-login.page.scss
  src/app/modules/user/pages/user-signup/user-signup.page.html
  src/app/modules/user/pages/user-signup/user-signup.page.scss
  src/app/modules/user/pages/user-signup/user-signup.page.ts
  src/theme/variables.scss
Labels: Enhancement

#220 updated ui and password requirements
  src/app/modules/user/pages/user-signup/user-signup.page.html
  src/app/modules/user/pages/user-signup/user-signup.page.ts
Labels: Enhancement, Priority: High, Status: Code Review, Effort: Easy, Role: Developer

#212 add user-registration form
  src/app/core/data/country.ts
  src/app/core/data/phone.ts
  src/app/models/account.model.ts
  src/app/modules/account/pages/registration/components/group-registration/group-registration.component.html
  src/app/modules/account/pages/registration/components/group-registration/group-registration.component.ts
  src/app/modules/account/pages/registration/components/user-registration/user-registration.component.html
  src/app/modules/account/pages/registration/components/user-registration/user-registration.component.ts
Labels: Status: Code Review, Role: Developer

#221 Tech debt
  src/app/app.routes.ts
  src/app/core/guards/auth.guard.ts
  src/app/core/services/auth-store.service.ts
  src/app/modules/account/pages/login/login.page.html
  src/app/modules/account/pages/login/login.page.scss
  src/app/modules/account/pages/login/login.page.spec.ts
  src/app/modules/account/pages/login/login.page.ts
  src/app/modules/account/pages/signup/signup.page.html
  src/app/modules/account/pages/signup/signup.page.scss
  src/app/modules/account/pages/signup/signup.page.spec.ts
  src/app/modules/account/pages/signup/signup.page.ts
  src/app/modules/user/pages/user-dashboard/user-dashboard.page.ts
  src/app/shared/components/menu/menu.component.ts
Labels: Refactor

#222 updated forms
  src/app/modules/account/pages/login/login.page.html
  src/app/modules/account/pages/signup/signup.page.html
Labels: Bug, Priority: Critical, Effort: Easy, Role: Developer, Role: QA
